### ISSUE TITLE
Sales invoice should not submit without E-Invoice & E-way Bill if applicable for B2B Transaction

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#1045]
### Information about bug

We need this validation to ensure that if irn generation produces an error, it should not be submitted. Because thus many sales were submitted months ago but no irn was generated, we are unable to generate it, which is a problem for us.
For further versatility, perhaps you could include a setting for do not submit if irn is not generated.
@vorasmit 
### Version

ERPNext: v14.38.0 (HEAD)
Frappe Framework: v14.48.1 (HEAD)
India Compliance: v14.16.2 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Have a look at the recently introduced dashboard. This should help you keep a check on pending e-Invoices
https://discuss.frappe.io/t/new-features-enhancements-for-india-compliance/109654#enhancements-to-e-waybill-and-e-invoice-3

Refer to the e-invoice summary report for details related to e-invoice exceptions.

We would still like to stick with the current design, as e-Invoice could fail even if NIC is down, and we don't want your billing to suffer because of it. There is always an option to generate an e-invoice at a later date.

Moreover, we have recently introduced auto-retry functionality for e-Invoice, where it will auto-retry generation of e-Invoice every 5 minutes if it fails because of a timeout error.

Make sure you are on the latest versions to benefit from recent developments. Hope you find this helpful.
