### ISSUE TITLE
GST Cancelled Issue

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#1058]
### Information about bug

Hello,

there is an issue in which you resticted to create invoices if party has cancelled gstin then you should restrict at the time of Purchase Order creation because if my materials is received then we should have to make invoice.

Proposed Solution:

1) Make this as a setting like if you want to allow invoices for cancelled invoices or not.

2) Rescticed Purchase Order creation instead of Purchase Invoice so material will never be order.

![cancelled inv](https://github.com/resilient-tech/india-compliance/assets/111174201/270a45dc-bc6d-4a7e-9931-a00f6fcc11f0)

### Version

India Compliance: v14.16.2 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello,

We are already validating GSTIN in the following document types: 

- Quotation
- Sales Order
- Delivery Note
- Sales Invoice
- Purchase Order
- Purchase Receipt
- Purchase Invoice

In your case, Purchase Order may have been generated before the deployment of this feature.

Hope this helps.

**Comment by vorasmit** [comment]
Moreover,
The intention here is not to disallow transactions. 
But it's to disallow transactions with invalid or cancelled GSTINs.
This is so that you can remove/update GSTIN in the relevant party or address masters and book the correct invoice.

You can completely disable this functionality from GST Settings.
