### ISSUE TITLE
TDS Compliance API

### ISSUE THREAD

**Issue by shahns** [resilient-tech/india-compliance#1076]
### Is your feature request related to a problem? Please describe.

I am looking for possibility to integrate TDS compliance apis with ERPNext and this this app would be the right place to have such functionality.

Is there any plan to implement such functionality?

### Describe the solution you'd like

One of the candidate solution can be found at:
https://developer.sandbox.co.in/docs/tds-compliance-api-guide

**Comment by vorasmit** [comment]
Hi,

This is definitely good to have and we have already studied these options.

However, they don't offer consistent pricing.
eg: It could cost as much as Rs 800 to file one TDS Return by using just one API
https://developer.sandbox.co.in/docs/e-file-tds-return-submit-job#wallet-charges

This is due to a monopoly from TIN FC here, where they themselves charge exorbitant prices.

To begin with, as a best-case scenario, we can offer an XLSX report generation utility or FUV generation facility from within ERP, which can be uploaded to file TDS returns or can be shared with CAs. 

To conclude, any form of TDS Integration to directly file TDS returns is not on the plans because of the above reason. However, we may support other TDS utilities like PAN or TAN validations if need be.

**Comment by shahns** [comment]
Hi Smit,
Thanks for the clarification. I’ll close this issue for now. May be we can reopen it in future, if there is friendly pricing options from any provider.

**Comment by eskhool** [comment]
Hi,

reopening to make this thread the one to explore the other options you suggested. Other TDS software providers are also using the FUV approach which makes it fairly simple.

Any update on the roadmap if any, or won't-do?

I can open another issue if that makes more sense but since both involve filing TDS returns, made sense to keep continuity. @vorasmit

**Comment by vorasmit** [comment]
FUV generation is not possible in the python environment and requires java as far as I know. Hence this currently not in the plans.

Our first objective is to streamline TDS workflow and it's visibility in ERPNext, and then we can support exporting this to excel which can be directly used to import in other utilities for filing return say TDSMAN, etc.
