### ISSUE TITLE
HSN code should set Item tax

### ISSUE THREAD

**Issue by siddhpant** [resilient-tech/india-compliance#1186]
### Is your feature request related to a problem? Please describe.

Currently, setting HSN code doesn't set item tax, which has to be set manually. If not done, there can be surprises during invoicing.

### Describe the solution you'd like

Setting HSN code for an item should set it's tax rate.

That can also potentially be made immutable as HSN determines the rate.

**Comment by ljain112** [comment]
Hello,

- Taxes for items are automatically set on save if they're defined in the HSN code and absent in the Item.
- There's a custom button in the HSN Code document allowing for tax updates in all Items associated with that HSN Code.
![image](https://github.com/resilient-tech/india-compliance/assets/108322669/f297c4d9-e0f8-4065-bd88-bf7896f43837)

- The tax rate cannot be made immutable due to instances where two different tax rates are used for the same HSN Code.

Hope this helps.

Regards,
Lakshit Jain

**Comment by siddhpant** [comment]
Couple of questions here:

1. Why are tax rates not set in HSN code already? It is very counter-intuitive to provide a list of HSN codes but not the associated tax rates, as HSN code is used in GST for taxation purposes. The T in GST stands for Tax. (If you want a list, it's probably just a matter of scraping [CBIC website](https://cbic-gst.gov.in/gst-goods-services-rates.html) and generating a JSON.)
2. There cannot be two tax rates for same HSN code. HSN code is a primary key. Which instances are you referring to?

**Comment by vorasmit** [comment]
- eg: Lookup for HSN 9603 in your link.

- Tax rates even change based on item rates.
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/27dd6613-5c95-47c5-a85d-a3e8fcbc5289)

- This changes often and it means we need to keep this updated. Not everyone prefers to update their server every month or quarter and would still expect this to be correct.

- Moreover, Govt gives the flexibility to use partial HSN codes, 4 digits and 6 digits. This may not have consistent tax rates across all HSN codes there. Users may use a 4-digit HSN code and have incorrect tax here.

There are only a few HSN codes that businesses need to worry about, and knowing they have to maintain this, they would do this properly. Even if we did do this partially, UX here would be sub-optimal and confusing.

The objective here is to give users the ability to automate this and update tax rates when they change.

**Comment by siddhpant** [comment]
Alright, thanks for the explanation. 

But could you add an alert when adding HSN informing that the tax rate is not set, or set item tax manually if HSN doesn't have tax rate? That will reduce surprises and also inform of the correct practice.

**Comment by vorasmit** [comment]
As per the current design, you need not select item tax for all items.
- From the sales taxes and charges template, tax accounts (CGST / IGST) and the default tax rate are chosen.
- From item tax template --> Tax rate is overridden for the accounts. This may not always be required.

Hence giving an alert makes less sense.

We'll improve documentation around this so that it's more clear.

**Comment by siddhpant** [comment]
Consider there are 5 products, and one of them has a different HSN and tax rate, say 12% default and 18% for the one product.

If the item tax rate is not set, the invoicing will apply the default tax of 12% rate on all the 5 items, but one item should have 18% tax.

The non-technical user expects 18% tax would be calculated since he set the HSN and doesn't know that item tax should also be set, as there is no visible cue about it when creating item. But here, 12% tax will be calculated.
