### ISSUE TITLE
GSPERR300 : Ei : GSPGSTDOWN

### ISSUE THREAD

**Issue by nilprakash** [resilient-tech/india-compliance#1357]
Getting this error while generating e-invoice, please help

**Comment by ljain112** [comment]
The issue you've mentioned happens because the API service is down on the Govt's side. In that scenario, neither the GSP (Adaequare) nor the ASP (Resilient Tech) can do much about it. Our only recommendation when such an issue arises is to try again after some time (maybe an hour or so).

If it's urgent, you may need to generate the e-Invoice manually from the Govt. portal.
