### ISSUE TITLE
Bounce Cheque Management in payment entry

### ISSUE THREAD

**Issue by GopalKedia2020** [resilient-tech/india-compliance#1916]
### Is your feature request related to a problem? Please describe.

Hi,

You must be aware of how Indian businesses operate; it's very common for customers to bounce cheques, especially in our industry. As per the current steps, what I understood is that first, we have to delink the invoice from the payment, pass a normal journal entry for the bounced cheque along with bounce cheque charges, and nullify the old payment entry using a journal entry only. Then, create a new payment entry for the invoice(s).

Instead of so many steps, can we have a simplified option in ERPNext, so that we can handle everything related to a payment in a single payment entry, and customers can see how many times their cheque got bounced in the ledger, so that we can claim the bounce charges from them too.

### Describe the solution you'd like

We can create an option to create a reverse payment entry along with a user-selectable option to add a penalty/charges (added to the party's account) and a note field, and it automatically delinks the invoices too from the payment entry.

Once this is done, we can have a new option to re-create a payment entry with a new date and the same old data. This will streamline the operations related to payment entry.

Please note: we can use some generic wordings so that it can be relatable to all other ERPNext users.

**Comment by vorasmit** [comment]
Hello @GopalKedia2020,

I understand the issue you are facing. This is best handled in ERPNext App, as this will be useful to many businesses outside India also.

Better place to put this issue to action would be:
https://github.com/frappe/erpnext/issues

Unfortunately, we are unable to transfer the issue, and hence it's best created again in ERPNext.

You can keep you issue with more detailed options or settings, so that it gets some traction faster.
