### ISSUE TITLE
Patches Not defined in patches.txt

### ISSUE THREAD

**Issue by chechani** [resilient-tech/india-compliance#208]
Patches Not defined in patches.txt

Due to this we can not save new address and update company PAN
1. IN Company Doctype Error is "AttributeError: 'Company' object has no attribute 'gstin'"
2. IN Address Doctype error is "AttributeError: 'ERPNextAddress' object has no attribute 'gst_category'"

**Comment by sagarvora** [comment]
The patches you're seeing as of now are not _designed_ to be put in `patches.txt`, since they are post-install patches.

Did the installation complete successfully for you? You would've seen this message if it did:
**Thank you for installing India Compliance!**

In this case, it seems like the custom fields did not get properly inserted during installation for you. You can run the following code in `bench console` to achieve this manually:

```python
from india_compliance.gst_india.setup import after_install
after_install()
frappe.db.commit()
```

Please note that you may have to reset GST settings after running above code.

**Comment by chechani** [comment]
Thanks ...It resolved the issue
But I had to revert back to erpnext beta 5 and frappe beta 4 as I was getting other error related to Image upload

[AttributeError: module 'PIL.Image' has no attribute 'Resampling']

**Comment by chechani** [comment]
Another question.

In GST settings we can set only one of each Input, Output and RCM.

What if we maintain separate GST ledger for each Tax rate like CGST @ 2.5%, SGST@2.5 %, IGST @ 5% and so on for 12, 18 and 28 Rates?

Current GST settings does not allow to have multiple Inputs and Outputs?

Is there any solution for that?

**Comment by sagarvora** [comment]
Please refer to this post on the ERPNext forum:
https://discuss.erpnext.com/t/proposed-breaking-changes-to-india-specific-features/87025

This is going off-topic. Kindly create a new issue if you want to discuss this further - so that others can search the issue by title.
