### ISSUE TITLE
Known Issue: Errors related to `python-barcode` with bench v5.14.0

### ISSUE THREAD

**Issue by dpk404** [resilient-tech/india-compliance#213]
I have tried installing this app as suggested by frappe while upgrading to version 14 but on installation, it gives the following output
`usage: python-barcode [-h] [-v] {create, list} ...`
`python-barcode: error: argument {create,list}: invalid choice: 'frappe.utils.bench_helper' (choose from 'create', 'list')
`
And after this, it shows up on almost every bench command

**Comment by vorasmit** [comment]
This issue is unrelated to this app and there is a problem with your upgrade or installation and 
Post a [discuss issue](https://discuss.erpnext.com/) / take an expert advice for your installation.

**Comment by sagarvora** [comment]
Hello,

It seems like you installed the app incorrectly. Please share your installation steps here.

`python-barcode` is a dependency in this app, but we don't use it as a CLI. Perhaps your customisations may be conflicting with the app's installation.

**Comment by dpk404** [comment]
I thought so
> Perhaps your customisations may be conflicting with the app's installation.

But even with a fresh installation, it's the same.
On fresh go I have installed the following apps:
erpnext v14
payments
hrms
india-compliance(at last)

**Comment by sagarvora** [comment]
- Which python version are you using? v14 requires Python 3.10
- Did you retry installation in the same bench? Perhaps it's a bench level error
- `payments` is a requirement for ERPNext v14. Did you install it first?

In any case, we can't seem to replicate the issue in our CI - nor has it been reported by other users. It seems increasingly likely that it's an installation issue. [ERPNext forum](https://discuss.erpnext.com/) is better suited for such queries. Please let us know if you think this issue is specific to India Compliance and needs to be resolved by us, we will reopen it.

**Comment by sagarvora** [comment]
Downgrading to bench v5.12 should fix the issue for now. It should get fixed in upcoming versions by following PR:
https://github.com/frappe/bench/pull/1360

Also refer: https://discuss.erpnext.com/t/python-barcode-error-while-installing-with-erpnext-v14/92981

**Comment by sagarvora** [comment]
Update: this issue has been fixed in bench v5.14.1
