### ISSUE TITLE
Customer GST Suspended

### ISSUE THREAD

**Issue by agastyaagro** [resilient-tech/india-compliance#2319]
Dear Sir

As per the GST portal the mentioned GST number 36EKFPR7657F1ZM is showing active but in ERP portal it is showing under suspended

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjdmZDEzZTJhNmFiOWVlZjU1OTU3NTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3IiwicHJvZHVjdElkIjoiIn0.x0M1EgJERSmNyxEUspkT9dJvUUg9C5jGQtQINNjEwrA">Huly&reg;: <b>IC-2432</b></a></sub>

**Comment by vorasmit** [comment]
We are aware that such an issue could occur and is already fixed. This is released in v14.28.0 and v15.9.0.
https://github.com/resilient-tech/india-compliance/pull/2198

**Issue:**
We used to prioritise e-Invoice API for GSTIN Status which may not be latest as per GST Portal (because there are restrictions on direct search). You can manually update the GSTIN Status on e-Invoice portal, and then refresh the same on your ERPNext site (as a temporary fix).

https://einvoice1.gst.gov.in/Others/TaxpayerSearch

**How is the issue fixed?**
On hard refresh (click of refresh button manually), we now prioritise API as per GST Portal. You can update your app and check if the issue still persists.
