### ISSUE TITLE
Single Input and Output GST accounts

### ISSUE THREAD

**Issue by ishanloya** [resilient-tech/india-compliance#255]
In v14, we can only have single Input/Output/RCM CGST/SGST/IGST accounts defined under GST settings. However, a company may have multiple GST numbers. In this case we need to have separate GST ledgers to track input/output GSTIN-wise. How can we go about this?

**Comment by ishanloya** [comment]
Can I already upgrade to v14 or should I wait for this pull request to be merged? What exactly is the impact of adding GST accounts to the GST settings page? Does it impact my ledgers in any way or simply helps with automation/validation/reporting?

**Comment by sagarvora** [comment]
Hello @ishanloya 👋🏼 

Transferring existing balances from GSTIN-wise accounts into a single account specified in GST settings is a requirement because this impacts how the taxable value and taxes are calculated in v14 (for e-Waybill, e-Invoice and GST Reports).

Having a single account isn't going to affect much. Once the linked PR is merged, you'll get new reports called GST Ledger and GST Balance to get GSTIN-wise data (similar General Ledger and Trial Balance). These reports will be based on the Company GSTIN field. This field is already present in all transactions except for Journal Entry (where it will be added soon). So once you specify the GSTIN in Journal Entries for the current period, you'll be good to go.



> Can I already upgrade to v14 or should I wait for this pull request to be merged?

Yes, you can upgrade. But you'll need to transfer existing account balances. Think of GSTIN as an accounting dimension instead of a cause for maintaining separate accounts.

**Comment by ishanloya** [comment]
Thanks for your reply @sagarvora 

It'll be good to have this feature. For now though, if an organisation isn't using e-waybill, e-invoicing or GST reports from ERPNext directly then having a single account in GST settings won't make any difference right?

**Comment by vorasmit** [comment]
Yes, true.

Accounts are used for validations and appropriate tax calculations, which affects further processes.
If you are not using any of those, you can ignore GST Accounts settings.

**Comment by pioneerpathan** [comment]
Hello Sagar and Smit,

Kudo to your team for the efforts and work done for the India Compliance app.

Actually, We are facing the same kind of issue. Till now we had a single ledger of CGST for input and output. Same for SGST and IGST. Now in the latest upgrade, we see the "Account Type" as a separate column in GST Setting. Since we have a single ledger/account for each type of GST tax category, how we can configure GST setting while upgrading in between the financial year? GST setting is not allowing to specify the same ledger as an INPUT and OUTPUT account type.
