### ISSUE TITLE
PurchaseInvoice object has no attribute 'is_reverse_charge'

### ISSUE THREAD

**Issue by nrhdasa** [resilient-tech/india-compliance#257]
![image](https://user-images.githubusercontent.com/40687270/192761978-80e6c175-12d0-4877-b9c9-178801b2bde7.png)

AttributeError: 'PurchaseInvoice' object has no attribute 'is_reverse_charge'

File \\\"apps/india_compliance/india_compliance/gst_india/overrides/transaction.py\\\", line 656, in validate_reverse_charge_transaction\\n    if not doc.is_reverse_charge:\\nAttributeError: 'PurchaseInvoice' object has no attribute 'is_reverse_charge'\\n

Please check.

**Comment by sagarvora** [comment]
Hello,

It seems like the system generated custom field `is_reverse_charge` didn't get created for you. This can happen due to one of the following reasons:
- After install script not completed successfully.
- Custom fields being overwritten by a custom app, through something like `custom/purchase_invoice.json` for example.

This is the code responsible for creating this field:
https://github.com/resilient-tech/india-compliance/blob/develop/india_compliance/gst_india/constants/custom_fields.py#L93:L99

If you want to re-sync the custom fields for India Compliance, just execute the following code in your bench instance (e.g. `frappe-bench`):
```
bench execute india_compliance.gst_india.setup.create_custom_fields
```

**Comment by vorasmit** [comment]
comment here if this is still not yet resolved.

**Comment by nrhdasa** [comment]
Yes, it is working fine now after running this script. Thanks. Sorry for replying late.
