### ISSUE TITLE
GST Tax Rate (child) Table in  GST HSN Code is removed in v14

### ISSUE THREAD

**Issue by jigneshpshah** [resilient-tech/india-compliance#321]
GST Tax Rate Table introduced in below PR but was removed in v14 / India Compliance. 
https://github.com/frappe/erpnext/pull/30978
>Reason for Introduction of GST Tax Rate Table
> 1. SEZ and Export Invoices without payment of tax in GSTR-1 report
> Currently, SEZ invoices without payment of tax did not use to show up in the GSTR-1 report since no GST was applied in it, this PR fixes that, SEZ and Export invoices (without payment of tax) also showed tax rates as 0 as no GST was applied. This was incorrect, invoices even without payment of taxes should be reported based on their HSN tax rate
> 
> For this have introduced a new table GST Tax rate in GST HSN Code doctype which will be used to fetch GST rates for items in such invoices

can refer the code below
https://github.com/frappe/erpnext/blob/6d1ae68d703fa654c76a4474de2eb401c26a8b16/erpnext/regional/report/gstr_1/gstr_1.py#L1175

@sagarvora  could you please guide how this case will be handled now ?

**Comment by vorasmit** [comment]
Hello,

Said PR was introduced to have tax rates for SEZ without tax payment in GSTR-1.
It also fixed scenarios where the invoice was not captured in GSTR-1 (as you rightly pointed out).

So, the fix is implemented but not the feature.

Hence, GSTR1 will show SEZ without tax payment in GSTR-1 at 0%.

Having a tax rate for SEZ (without tax payment) is not required, hence the feature was dropped.

**Comment by sagarvora** [comment]
I'm closing this issue. But you can still comment here if you have further concerns.
