### ISSUE TITLE
After getting the India compliance app & get stuck on this error.

### ISSUE THREAD

**Issue by vignesh235** [resilient-tech/india-compliance#326]
![image](https://user-images.githubusercontent.com/95606753/200300633-48bab347-4178-4019-8bc5-141305e9b298.png)
@ankush @sagarvora

**Comment by vignesh235** [comment]
Did I miss anything 🤔?

**Comment by sagarvora** [comment]
Please refrain from creating new issues. If it is related to the existing issue, you can comment there even if the issue is closed.

(We close issues that are not bugs or feature requests.)

---

It seems like you have vue3 instead of vue2 required for version 14. Try running `bench setup requirements --node`
