### ISSUE TITLE
Delivery Note Connected with Sales Invoice not updated with eWayBill number

### ISSUE THREAD

**Issue by ganz007** [resilient-tech/india-compliance#414]
While the eWayBill number is auto generated and populated when the Sales invoice is submitted, the connected Delivery note has the same field blank. It would be appropriate to have the eWaybill number populated here also, to avoid any duplicity.

**Comment by vorasmit** [comment]
Hello,

e-Waybill is per document and it would be incorrect to show it on the different document for which it's not generated. Also, there is one to many relationship between the Sales Invoice and Delivery Note, which cannot be generalised.

How can this be implemented?
- Customize to your requirements.
- Where you use the same items in the delivery note, you can have a secondary print format in the Sales Invoice with heading Delivery Challan.

Hence we don't copy it back to Delivey Note. This behaviour is intentional.
