### ISSUE TITLE
GSTIN Missing in Invoice Address

### ISSUE THREAD

**Issue by clayrisser** [resilient-tech/india-compliance#462]
I'm not sure why, but the gstin number is missing when I try and print a GST Tax Invoice. The GST number is saved in the address and even shows up in the invoice document, but it does now show up when I try adn print with the `GST Tax Invoice` format.

**Comment by sagarvora** [comment]
**GST Tax Invoice** just copies whatever is stored in the `address_display` and `company_address_display` field. If your address is showing up without GSTIN there, it's likely to be because of a problematic [address template](https://docs.erpnext.com/docs/v14/user/manual/en/setting-up/print/address-template). This is the default that gets installed, when installing the app:

https://github.com/resilient-tech/india-compliance/blob/bd9ec6da0cc497d6716fd48a2e0b54f44fd5325d/india_compliance/gst_india/data/address_template.html

Since this doesn't seem like a bug / feature request, I'll be closing this issue. The [community forum](https://discuss.frappe.io/c/erpnext/india-compliance/65) is better suited for such queries. Feel free to comment here if you think the issue was closed erroneously.

You may also consider emailing us at _hello at indiacompliance dot app_ for paid support.

**Comment by clayrisser** [comment]
Oh wow, thanks. This helped so much. It's working for me now. I just had to update the address template manually.
