### ISSUE TITLE
Update GST HSN Code not update in Item Master

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#554]
### Information about bug

https://user-images.githubusercontent.com/21578167/229518994-d8e25b29-0807-49f5-bbe6-f59e01e237c0.mov

HSN Code not updating the item masters

### Version

ERPNext: v14.20.0 (version-14)
Frappe Framework: v14.30.0 (version-14)
Gatepass: v0.0.1 (main)
Frappe HR: v14.2.0 (version-14)
India Compliance: v14.5.0 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
I think this might be failing due to your issue with background workers. It works as expected in local testing. This is the relevant code that enqueues the item updation:

https://github.com/resilient-tech/india-compliance/blob/622737e17a85162da6ed706866b5eadea8cad54b/india_compliance/gst_india/doctype/gst_hsn_code/gst_hsn_code.py#L17

Note that this may also fail if the user clicking the button doesn't have permissions for all the items linked to this HSN code.
