### ISSUE TITLE
Lower-deduction-certificate not found Error

### ISSUE THREAD

**Issue by jaydeep-sigzen** [resilient-tech/india-compliance#596]
### Information about bug

We are facing error like lower-deduction-certificate not found and The resource you are looking for is not available. I am still confusing like this doctype is part of India Compliance Or ERPNext? As per your earlier issue this must be part of India Compliance but we couldn't find under that.

Please refer below screenshot for your reference. 
<img width="645" alt="Screenshot 2023-04-14 at 4 09 18 PM" src="https://user-images.githubusercontent.com/127377825/232022756-9233acd3-2533-4f45-8435-6ac870d407db.png">

### Version

**Below are the versions we are using.**
1. ERPNext: v14.20.1 
2. Frappe Framework: v14.31.0
3. India Compliance: v14.5.1 

### Relevant log output / Stack trace / Full Error Message.

```shell
Not found
Page lower-deduction-certificate not found
The resource you are looking for is not available
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaydeep-sigzen** [comment]
@sagarvora Any Update on this? Can you please help on this.

**Comment by sagarvora** [comment]
The doctype is a part of ERPNext as of today (it is yet to be moved to India Compliance). 

- Can you find it in DocType list?
- Can you see it in Role Permissions Manager?

---

Since we cannot replicate this as of now, I will keep the issue in **Closed** state and remove the `bug` label (as per policy). If it is later found to be a bug, we will revert this action. Note that you can still comment on this issue in **Closed** state.
