### ISSUE TITLE
E-Invoice & E-Way bill API Issue

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#641]
### Information about bug

**While creating E-Invoice & E-way bill below error show**
<img width="883" alt="image" src="https://user-images.githubusercontent.com/119041865/235302545-d6ab7613-2cb3-4ba6-8ef6-1b715341a79d.png">

we are purchasing API credits on India Compliance Account but facing this issue, our site is hosted on local server
Encryption key is updated on local site as per database restored

### Version

ERPNext: v14.22.2 (version-14)
Frappe Framework: v14.33.1 (version-14)
India Compliance: v14.6.0 (version-14)
Payments: v0.0.1 (develop)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Please share full traceback.

**Comment by sagarvora** [comment]
This is most likely an invalid issue which has nothing to do with India Compliance itself. You may have updated some password before setting the correct encryption key. So out of the `api_secret` and `credentials` in GST Settings both passwords may not be using the same encryption key.

Issue may not happen if you change key first and then restore again. In any case, it cannot be treated as a bug, so this issue is being closed. Please consider purchasing support to help debug such issues.
