### ISSUE TITLE
cannot create opening entry Tax Accounts CGST, IGST, SGST

### ISSUE THREAD

**Issue by bhavyajicomputers** [resilient-tech/india-compliance#644]
cannot create opening entry Tax Accounts CGST, IGST, SGST , these accounts not available in journal entry  for creating opening entry, Kindly do needful

**Comment by vorasmit** [comment]
Thank you for submitting your issue. However, after reviewing it, we have determined that it is not related to the India Compliance App. Therefore, we kindly request that you post your query on our discussion forum at https://discuss.frappe.io/ to receive free community support.

Please note that if you need priority support, you can purchase it from Frappe or us. Additionally, we would like to remind you that your issue appears to be in violation of our issue guidelines, which you can find here: https://github.com/frappe/erpnext/wiki/Issue-Guidelines.

We kindly request that you follow these guidelines in the future so that we can keep our repository organized and easy to navigate for all users.

Thank you for your understanding.
