### ISSUE TITLE
Invalid 'depends_on' when editing an item

### ISSUE THREAD

**Issue by asifmohtesham** [resilient-tech/india-compliance#734]
### Information about bug

After installing `version-14`, getting error:

`Invalid 'depends_on' expression`

![image](https://github.com/resilient-tech/india-compliance/assets/30242354/d50b39ab-e9bf-4345-ab0e-8b2885d81d05)

Figured that this is causing the error:
DocType: Item
Field: HSN/SAC
Property Depends On: `eval:gst_settings.validate_hsn_code`

### Version

Frappe Framework: v14.33.1
ERPNext: v14.22.2
India Compliance: v14.8.0 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
You don't seem to have installed the India Compliance app yet (it's not visible in the versions you posted). Have you?

This is most likely an installation issue, rather than a bug. Please create a topic on the [discussion forum](https://discuss.frappe.io/c/erpnext/india-compliance/65) or email us for paid support.

**Comment by asifmohtesham** [comment]
> You don't seem to have installed the India Compliance app yet (it's not visible in the versions you posted). Have you?
> 
> This is most likely an installation issue, rather than a bug. Please create a topic on the [discussion forum](https://discuss.frappe.io/c/erpnext/india-compliance/65) or email us for paid support.

It is installed, it didn't copy the app version.

![image](https://github.com/resilient-tech/india-compliance/assets/30242354/2929f6e9-cfb1-4824-b650-665a5c82d584)
