### ISSUE TITLE
GST SALES REGISTER 

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#755]
### Information about bug

Whenever in customer "IS INTERNAL CUSTOMER" checkbox is ticked those transaction should not be recorded in GST SALES REGSITER Report.
These transaction should not be considered as sales. 

### Version

ERPNext: v14.26.0 (version-14)
Frappe Framework: v14.37.0 (version-14)
India Compliance: v14.8.0 (version-14-dex)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Hi @asoral,

The GST Sales Register is designed to document all sales invoices, and where GST is relevant, it will be displayed in the corresponding tax sections. 

Could you clarify the particular scenario you’re interested in? Remember that when branch transfers occur with different GSTINs, they should be included in GSTR-1 reports. Could you explain why your proposed solution would provide an improvement?

**Comment by asoral** [comment]
@vorasmit but **Gst Purchase Register** Report Not Fixed Also "**Hsn Wise Summary Of Outward Supplies**" still Showing Internal Customer Invoices data

**Comment by asoral** [comment]
@vorasmit https://github.com/resilient-tech/india-compliance/pull/878.I fixed those 2 report

**Comment by asoral** [comment]
@vorasmit https://github.com/resilient-tech/india-compliance/pull/880. fixed those 2 report

**Comment by vorasmit** [comment]
This is not the expected behaviour.
Please note that we are already making a check over here.
https://github.com/resilient-tech/india-compliance/blob/develop/india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py#L169

Please note that all invoices with Internal Customers are not supposed to be excluded.
There is a possibility of invoices from one state to another which is required to be reported in GSTR-1.

Looks like you have an inappropriate implementation and hence you are facing this issue.

**Comment by asoral** [comment]
> This is not the expected behaviour. Please note that we are already making a check over here. https://github.com/resilient-tech/india-compliance/blob/develop/india_compliance/gst_india/report/hsn_wise_summary_of_outward_supplies/hsn_wise_summary_of_outward_supplies.py#L169
> 
> Please note that all invoices with Internal Customers are not supposed to be excluded. There is a possibility of invoices from one state to another which is required to be reported in GSTR-1.
> 
> Looks like you have an inappropriate implementation and hence you are facing this issue.

@vorasmit Thanks For Reply. I will Change Hsn Wise Summary Of Outward Supply Report.but Gst Purchase Register Is ok
